"""Initial migration: accounts, categories, transactions, transfers

Revision ID: 9da6345225f6
Revises: 
Create Date: 2026-01-31 15:55:06.107867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9da6345225f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.Enum('INGRESO', 'GASTO', 'AMBOS', name='categorytype'), nullable=False),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('categoria_padre_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_padre_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_index('idx_categorias_padre', ['categoria_padre_id'], unique=False)
        batch_op.create_index('idx_categorias_tipo', ['tipo'], unique=False)

    op.create_table('cuentas',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('DEBITO', 'CREDITO', 'EFECTIVO', name='accounttype'), nullable=False),
    sa.Column('divisa', sa.String(length=3), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacciones',
    sa.Column('tipo', sa.Enum('INGRESO', 'GASTO', name='transactiontype'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cuenta_id', sa.UUID(), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.create_index('idx_transacciones_categoria', ['categoria_id'], unique=False)
        batch_op.create_index('idx_transacciones_cuenta_fecha', ['cuenta_id', 'fecha'], unique=False)
        batch_op.create_index('idx_transacciones_cuenta_tipo', ['cuenta_id', 'tipo'], unique=False)
        batch_op.create_index('idx_transacciones_fecha', ['fecha'], unique=False)

    op.create_table('transferencias',
    sa.Column('cuenta_origen_id', sa.UUID(), nullable=False),
    sa.Column('cuenta_destino_id', sa.UUID(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_destino_id'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_origen_id'], ['cuentas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transferencias', schema=None) as batch_op:
        batch_op.create_index('idx_transferencias_destino', ['cuenta_destino_id'], unique=False)
        batch_op.create_index('idx_transferencias_fecha', ['fecha'], unique=False)
        batch_op.create_index('idx_transferencias_origen', ['cuenta_origen_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transferencias', schema=None) as batch_op:
        batch_op.drop_index('idx_transferencias_origen')
        batch_op.drop_index('idx_transferencias_fecha')
        batch_op.drop_index('idx_transferencias_destino')

    op.drop_table('transferencias')
    with op.batch_alter_table('transacciones', schema=None) as batch_op:
        batch_op.drop_index('idx_transacciones_fecha')
        batch_op.drop_index('idx_transacciones_cuenta_tipo')
        batch_op.drop_index('idx_transacciones_cuenta_fecha')
        batch_op.drop_index('idx_transacciones_categoria')

    op.drop_table('transacciones')
    op.drop_table('cuentas')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index('idx_categorias_tipo')
        batch_op.drop_index('idx_categorias_padre')

    op.drop_table('categorias')
    # ### end Alembic commands ###
